on:
  push:
    branches: ["*"]
  pull_request:

jobs:
  run-tests:
    uses: ./.github/workflows/run-tests.yml

  check-conventional-commits:
    uses: armakuni/github-actions/.github/workflows/check-conventional-commits.yml@v0.4.1

  create-release:
    needs:
      - run-tests
      - check-conventional-commits
    if: github.ref == 'refs/heads/main'
    uses: armakuni/github-actions/.github/workflows/tag-and-release.yml@v0.4.1
    secrets:
      # doesn't have to be a secret, but it's generally best practice to keep it hidden
      AWS_ACCOUNT_ID: ${{ secrets.ARMAKUNI_AWS_PROD_ACCOUNT_ID }}