on:
  workflow_call:
    secrets:
      AWS_ACCOUNT_ID:
        required: true

permissions:
  id-token: write # This is required for requesting the JWT
  contents: read  # This is required for actions/checkout

env:
  go-version: "^1.21.1"

jobs:
  go-fmt:
    name: run lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v4
        with:
          go-version: ${{ env.go-version }}
      - name: gofmt
        run: gofmt -s -l .

  go-test:
    if: github.ref == 'refs/heads/main'
    name: run tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v4
        with:
          go-version: ${{ env.go-version }}

      - name: Get Repository Name
        id: get-repository-name
        run: |
          full_name="${{ github.repository }}"
          repository_name=${full_name#*/}
          echo "repository-name=$repository_name" >> "$GITHUB_OUTPUT"

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          role-to-assume: arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/${{ steps.get-repository-name.outputs.repository-name }}-github-actions
          role-session-name: terratest-session
          aws-region: eu-west-1

      - name: go test
        run: go test ./...
